version: '3.8'

services:
  webgoat:
    image: webgoat/webgoat
    ports:
      - "8080:8080"
    environment:
      - WEBGOAT_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - webgoat_net

networks:
  webgoat_net:
    driver: bridge