apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alerts.yml: |
    groups:
    - name: webgoat
      rules:
      - alert: WebGoatDown
        expr: up{job="webgoat"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "WebGoat is down"
          description: "WebGoat has been down for more than 1 minute"

    - name: kubernetes
      rules:
      - alert: NodeHighCPU
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for 5 minutes"

      - alert: PodCrashLooping
        expr: kube_pod_container_status_restarts_total > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{ $labels.pod }} is crash looping"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has restarted more than 5 times in 10 minutes"

      - alert: NodeHighMemory
        expr: 100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Node {{ $labels.instance }} memory usage is critically high"
          description: "Memory usage on {{ $labels.instance }} has exceeded 90% for 5 minutes."

      - alert: PersistentVolumeUsage
        expr: kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Persistent volume usage is high"
          description: "Persistent volume usage is above 85% for {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }}"
