apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'webgoat'
        metrics_path: '/WebGoat/actuator/prometheus'  
        static_configs:
          - targets:
              - '20.63.16.243:8080'  # External IP for WebGoat
              - 'webgoat.webgoat.svc.cluster.local:8080'  # Internal Kubernetes service for WebGoat
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kubernetes'
        kubernetes_sd_configs:
          - role: node
