apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'alertmanager:9093'

    rule_files:
      - /etc/prometheus/rules/*.yml

    scrape_configs:
      - job_name: 'alertmanager'
        static_configs:
          - targets: ['alertmanager:9093']

      - job_name: 'webgoat'
        metrics_path: '/WebGoat/actuator/prometheus'
        scheme: 'http'
        basic_auth:
          username: 'webgoat'        # Default WebGoat username
          password: 'webgoat'        # Default WebGoat password
        follow_redirects: true       # Handle 302 redirects
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets:
              - '20.151.79.23:31051'

      - job_name: 'prometheus'
        static_configs:
          - targets: ['20.151.79.23:31090']

      - job_name: 'kubernetes'
        scheme: https
        metrics_path: /metrics
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            regex: (.+)
            target_label: __address__
            replacement: ${1}:10250
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets:
              - '20.151.79.23:31080'

      - job_name: 'grafana'
        static_configs:
          - targets:
              - '20.151.79.23:31300'

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            regex: true
            source_labels: 
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          - action: replace
            regex: (https?)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: kubernetes_namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: kubernetes_pod_name

      - job_name: 'cadvisor'
        scheme: https
        metrics_path: /metrics
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            regex: (.+)
            target_label: __address__
            replacement: ${1}:18080
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)