apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'severity']  # Ajout de severity pour le groupement
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'discord'
      routes:
      - match:
          severity: critical
        receiver: 'discord'
        group_wait: 0s  # Envoi immédiat pour les alertes critiques
      - match:
          severity: warning
        receiver: 'discord'

    receivers:
    - name: 'discord'
      webhook_configs:
      - url: 'https://discord.com/api/webhooks/1310078253767200788/eQM3uF7CWp0On2wrQqDYZAxYoNkYDdppCBU9BibbIL2ZkM-S67MJb9oDNglMOwqss-P0'
        send_resolved: true # Envoi des résolutions d'alertes
        message: |
          {{ if eq .Status "firing" }}🔥 ALERTE {{ else }}✅ RESOLVED{{ end }}
          Alerte: {{ .GroupLabels.alertname }}
          Sévérité: {{ .GroupLabels.severity }}
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}