apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'discord'
      routes:
      - match:
          severity: critical
        receiver: 'discord'
      - match:
          severity: warning
        receiver: 'discord'

    receivers:
    - name: 'discord'
      webhook_configs:
      - url: 'https://discord.com/api/webhooks/1310078253767200788/eQM3uF7CWp0On2wrQqDYZAxYoNkYDdppCBU9BibbIL2ZkM-S67MJb9oDNglMOwqss-P0'
        send_resolved: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  discord.tmpl: |
    {{ define "discord.default.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
    {{ end }}

    {{ define "discord.default.message" }}
    {{ range .Alerts }}
    **Alert:** {{ .Labels.alertname }}
    **Severity:** {{ .Labels.severity }}
    **Description:** {{ .Annotations.description }}
    {{ if .Annotations.summary }}**Summary:** {{ .Annotations.summary }}{{ end }}
    {{ end }}
    {{ end }}