apiVersion: v1
kind: ConfigMap
metadata:
  name: webgoat-config
  namespace: webgoat
data:
  application.yml: |
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
          base-path: /WebGoat/actuator  
      endpoint:
        prometheus:
          enabled: true
    security:
      basic:
        enabled: false
    management.security.enabled: false