apiVersion: v1
kind: ConfigMap
metadata:
  name: webgoat-config
  namespace: webgoat
data:
  application.yml: |
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
      endpoint:
        prometheus:
          enabled: true