apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  namespace: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: webgoat
        image: webgoat/webgoat
        env:
        - name: WEBGOAT_PORT
          value: "8080"
        - name: WEBGOAT_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 8080