apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  namespace: webgoat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: webgoat/webgoat
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /WebGoat
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat
  namespace: webgoat
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webgoat
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webgoat-network-policy
  namespace: webgoat
spec:
  podSelector:
    matchLabels:
      app: webgoat
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP