apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  namespace: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: webgoat
        image: webgoat/webgoat
        env:
        - name: WEBGOAT_PORT
          value: "8080"
        - name: WEBGOAT_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /application.yml
          subPath: application.yml
      volumes:
      - name: config-volume
        configMap:
          name: webgoat-config