apiVersion: v1
kind: Service
metadata:
  name: webgoat
  namespace: webgoat
  annotations:
    service.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: webgoat