apiVersion: v1
kind: Service
metadata:
  name: webgoat
  namespace: webgoat
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 31051 
  selector:
    app: webgoat