apiVersion: v1
kind: Service
metadata:
  name: webgoat
  namespace: webgoat
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31051 
  selector:
    app: webgoat