- name: Configure WebGoat Environment
  hosts: webgoat
  become: yes
  tasks:
    - name: Clean up existing Docker repos
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/docker.list
        - /usr/share/keyrings/docker-archive-keyring.gpg
        - /usr/share/keyrings/docker.gpg

    - name: Clean apt lists
      command: rm -rf /var/lib/apt/lists/*

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove conflicting packages
      apt:
        name:
          - containerd.io
          - containerd
          - docker.io
        state: absent
        purge: yes
        force_apt_get: yes
        autoremove: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes