- name: Configure WebGoat Environment
  hosts: webgoat
  become: yes
  tasks:
    - name: Clean up existing Docker repos
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/docker.list
        - /usr/share/keyrings/docker-archive-keyring.gpg
        - /usr/share/keyrings/docker.gpg

    - name: Clean apt lists
      command: rm -rf /var/lib/apt/lists/*

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove conflicting packages
      apt:
        name:
          - containerd.io
          - containerd
          - docker.io
        state: absent
        purge: yes
        force_apt_get: yes
        autoremove: yes

    - name: Clean Docker and containerd directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /var/lib/containerd
        - /etc/docker
        - /etc/containerd

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory

    - name: Configure containerd
      shell: containerd config default | tee /etc/containerd/config.toml

    - name: Restart services
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
      with_items:
        - containerd
        - docker

    - name: Add user to docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Verify Docker installation
      command: docker run hello-world
      register: docker_test
      changed_when: false