---
- name: Configure WebGoat Environment
  hosts: webgoat
  become: yes
  vars:
    docker_user: azureuser

  tasks:
    - name: Add user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes