---
- name: Configure WebGoat Environment
  hosts: webgoat
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - git
          - python3-pip
        state: present

    - name: Add user to docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Install kubectl
      become: yes
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/

    - name: Create Kubernetes config directory
      file:
        path: /home/azureuser/.kube
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Clone WebGoat repository
      git:
        repo: https://github.com/AhmedGafsi09/WebGoat.git
        dest: /home/azureuser/WebGoat
        force: yes

    # Déploiement Kubernetes
    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present

    - name: Apply Prometheus configurations
      kubernetes.core.k8s:
        state: present
        src: "/home/azureuser/WebGoat/kubernetes/prometheus/prometheus-deployment.yaml"
        namespace: monitoring

    - name: Apply Grafana configurations
      kubernetes.core.k8s:
        state: present
        src: "/home/azureuser/WebGoat/kubernetes/grafana/grafana-deployment.yaml"
        namespace: monitoring