name: "Main / Pull Requests Build"

on:
  pull_request:
    paths-ignore:
      - '.txt'
      - 'LICENSE'
      - 'docs/**'
    branches: [ main ]
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: Pre-commit CI Lite
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

  build:
    needs: [ pre-commit ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: mvn --no-transfer-progress verify
