name: "Main / Pull Requests Build"

on:
  pull_request:
    paths-ignore:
      - '.txt'
      - 'LICENSE'
      - 'docs/**'
    branches: [ main ]
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Pre-commit checks
        id: pre-commit
        run: |
          pre-commit run --all-files || echo "Pre-commit check failed"

      - name: Record Pre-commit Status
        if: failure()
        run: echo "::warning file=pre-commit::Pre-commit checks failed, proceeding with pipeline"

  build:
    needs: [ pre-commit ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: mvn --no-transfer-progress verify
