name: "Deploy to VM"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 20.63.16.243
        username: azureuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Update system and install dependencies
          sudo apt update
          sudo apt install -y docker.io docker-compose git

          # Add user to docker group
          sudo usermod -aG docker $USER

          # Clone or update repository
          if [ ! -d ~/WebGoat ]; then
            git clone https://github.com/AhmedGafsi09/WebGoat.git ~/WebGoat
          else
            cd ~/WebGoat
            git pull
          fi

          # Deploy with Docker Compose
          cd ~/WebGoat
          sudo docker-compose down || true
          sudo docker-compose up -d

          # Verify deployment
          sudo docker ps