name: Deploy WebGoat to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the environment for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy WebGoat
        run: |
          ls -al
          kubectl apply -f /WebGoat/kubernetes
          kubectl rollout status deployment/webgoat --namespace webgoat

      - name: Get WebGoat service information
        run: |
          kubectl get service webgoat --namespace webgoat -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
