name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image for WebGoat"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 20.63.16.243 >> ~/.ssh/known_hosts

    - name: Reset and Clean Kubernetes
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          sudo kubeadm reset -f || true
          sudo apt-get remove -y kubelet kubeadm kubectl kubernetes-cni
          sudo apt-get autoremove -y
          sudo rm -rf /etc/kubernetes/
          sudo rm -rf ~/.kube/
        '

    - name: Install Dependencies on VM
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubelet kubeadm kubectl
          sudo apt-mark hold kubelet kubeadm kubectl
        '

    - name: Initialize Kubernetes Cluster
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=20.63.16.243
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
        '

    - name: Install Calico Network Plugin
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
        '

    - name: Wait for Node Ready
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          for i in {1..30}; do
            if kubectl get nodes | grep -q "Ready"; then
              echo "Node is Ready"
              exit 0
            fi
            echo "Waiting for node to be ready... ($i/30)"
            sleep 10
          done
          exit 1
        '

    - name: Deploy Applications
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          cd ~/WebGoat
          git pull
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f kubernetes/prometheus/ -n monitoring
          kubectl apply -f kubernetes/grafana/ -n monitoring
          kubectl apply -f kubernetes/webgoat/ -n webgoat
        '