name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 20.63.16.243 >> ~/.ssh/known_hosts

      - name: Deploy Monitoring Stack
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
            echo "Updating repository..."
            cd ~/WebGoat
            git pull

            echo "Creating namespaces..."
            kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
            kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -

            echo "Deploying Prometheus stack..."
            kubectl delete -f kubernetes/prometheus/ -n monitoring || true
            kubectl apply -f kubernetes/prometheus/prometheus-config.yaml
            kubectl apply -f kubernetes/prometheus/kube-state-metrics.yaml
            kubectl apply -f kubernetes/prometheus/prometheus-deployment.yaml
            
            echo "Deploying Grafana..."
            kubectl delete -f kubernetes/grafana/ -n monitoring || true
            kubectl apply -f kubernetes/grafana/grafana-deployment.yaml
            
            echo "Waiting for monitoring services..."
            kubectl wait --for=condition=ready pod -l app=prometheus -n monitoring --timeout=300s
            kubectl wait --for=condition=ready pod -l app=grafana -n monitoring --timeout=300s
            
            echo "Monitoring service ports:"
            kubectl get svc -n monitoring
          '

      - name: Deploy WebGoat
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
            cd ~/WebGoat
            
            echo "Removing old WebGoat deployment..."
            kubectl delete -f kubernetes/deployment.yaml || true
            kubectl delete -f kubernetes/service.yaml || true
            
            echo "Deploying new WebGoat..."
            kubectl apply -f kubernetes/deployment.yaml
            kubectl apply -f kubernetes/service.yaml
            
            echo "Waiting for WebGoat to be ready..."
            kubectl wait --for=condition=ready pod -l app=webgoat -n webgoat --timeout=300s || true
            
            echo "Service information:"
            echo "-------------------"
            echo "WebGoat service:"
            kubectl get svc -n webgoat
            
            echo "\nPrometheus service:"
            kubectl get svc -n monitoring prometheus
            
            echo "\nGrafana service:"
            kubectl get svc -n monitoring grafana
            
            echo "\nPod status:"
            kubectl get pods --all-namespaces
          '