name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 20.63.16.243 >> ~/.ssh/known_hosts

      - name: Deploy Monitoring Stack
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
            # Create namespaces
            kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
            kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -

            # Update repository
            cd ~/WebGoat
            git pull

            # Deploy monitoring stack
            echo "Deploying Prometheus and related services..."
            kubectl apply -f kubernetes/prometheus/prometheus-config.yaml
            kubectl apply -f kubernetes/prometheus/kube-state-metrics.yaml
            kubectl apply -f kubernetes/prometheus/prometheus-deployment.yaml
            
            # Deploy Grafana
            echo "Deploying Grafana..."
            kubectl apply -f kubernetes/grafana/grafana-deployment.yaml
            
            # Wait for monitoring services
            echo "Waiting for monitoring services to be ready..."
            kubectl wait --for=condition=ready pod -l app=prometheus -n monitoring --timeout=300s
            kubectl wait --for=condition=ready pod -l app=grafana -n monitoring --timeout=300s
            kubectl wait --for=condition=ready pod -l app=kube-state-metrics -n monitoring --timeout=300s

            # Get service info
            echo "Monitoring Services NodePorts:"
            kubectl get svc -n monitoring
          '

      - name: Deploy WebGoat
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
            cd ~/WebGoat
            
            # Deploy WebGoat
            echo "Deploying WebGoat..."
            kubectl apply -f kubernetes/deployment.yaml
            kubectl apply -f kubernetes/service.yaml
            
            # Wait for WebGoat to be ready
            echo "Waiting for WebGoat to be ready..."
            kubectl wait --for=condition=ready pod -l app=webgoat -n webgoat --timeout=300s
            
            # Get service info
            echo "WebGoat Service NodePort:"
            kubectl get svc -n webgoat
            
            # Verify all deployments
            echo "\nAll Deployments Status:"
            kubectl get pods --all-namespaces
            echo "\nAll Services Status:"
            kubectl get services --all-namespaces
          '