name: Deploy to K8s

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Copy Kubernetes files and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "20.63.16.243"
        username: "azureuser"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create directory if it doesn't exist
          mkdir -p ~/WebGoat/kubernetes

          # Clone or update repository
          if [ ! -d ~/WebGoat ]; then
            git clone https://github.com/AhmedGafsi09/WebGoat.git ~/WebGoat
          else
            cd ~/WebGoat
            git pull
          fi

          # Create namespace if it doesn't exist
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -

          # Deploy to Kubernetes
          cd ~/WebGoat
          kubectl apply -f kubernetes/ -n webgoat

          # Verify deployment
          kubectl get pods -n webgoat
          kubectl get services -n webgoat