name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image for WebGoat"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 20.63.16.243 >> ~/.ssh/known_hosts

    - name: Prepare Kubernetes Environment
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          # Disable swap
          sudo swapoff -a
          sudo sed -i "/swap/d" /etc/fstab

          # Reset existing Kubernetes cluster
          sudo kubeadm reset -f

          # Ensure containerd is running
          sudo systemctl restart containerd
        '

    - name: Initialize Kubernetes Cluster
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          # Initialize cluster
          sudo kubeadm init \
            --pod-network-cidr=192.168.0.0/16 \
            --apiserver-advertise-address=20.63.16.243

          # Setup kubeconfig
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config

          # Install Calico network plugin
          kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
        '

    - name: Deploy Applications
      run: |
        ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 '
          cd ~/WebGoat
          git pull
          
          # Create namespaces
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

          # Deploy applications
          kubectl apply -f kubernetes/prometheus/ -n monitoring
          kubectl apply -f kubernetes/grafana/ -n monitoring
          kubectl apply -f kubernetes/webgoat/ -n webgoat
        '