---
    name: Deploy WebGoat to Kubernetes
    hosts: webgoat
    become: yes
    tasks:
      - name: Create kubernetes directory
        file:
          path: /opt/webgoat/kubernetes
          state: directory
          mode: '0755'
    
      - name: Create WebGoat namespace
        kubernetes.core.k8s:
          name: webgoat
          api_version: v1
          kind: Namespace
          state: present
    
      - name: Deploy WebGoat application
        kubernetes.core.k8s:
          state: present
          definition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: webgoat
              namespace: webgoat
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: webgoat
              template:
                metadata:
                  labels:
                    app: webgoat
                spec:
                  containers:
                  - name: webgoat
                    image: webgoat/webgoat
                    ports:
                    - containerPort: 8080
                    resources:
                      limits:
                        cpu: "1"
                        memory: "1Gi"
                      requests:
                        cpu: "500m"
                        memory: "512Mi"
    
      - name: Create WebGoat Service
        kubernetes.core.k8s:
          state: present
          definition:
            apiVersion: v1
            kind: Service
            metadata:
              name: webgoat
              namespace: webgoat
            spec:
              type: LoadBalancer
              ports:
              - port: 8080
                targetPort: 8080
              selector:
                app: webgoat
    
      - name: Wait for deployment to be ready
        kubernetes.core.k8s_info:
          kind: Deployment
          name: webgoat
          namespace: webgoat
          wait: yes
          wait_timeout: 300
          wait_condition:
            type: Available
            status: "True"
    
      - name: Get service information
        kubernetes.core.k8s_info:
          kind: Service
          name: webgoat
          namespace: webgoat
        register: service_info
    
      - name: Display Service IP
        debug:
          msg: "WebGoat is available at: http://{{ service_info.resources[0].status.loadBalancer.ingress[0].ip }}:8080/WebGoat"
    