# name: CI/CD Pipeline

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Azure login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#       - name: Terraform Init and Plan
#         run: |
#           cd infrastructure
#           terraform init
#           terraform plan

#       - name: Terraform Apply
#         run: |
#           cd infrastructure
#           terraform apply -auto-approve

#       - name: Configure Kubernetes
#         uses: azure/k8s-set-context@v2
#         with:
#           method: service-account

#       - name: Deploy to Kubernetes
#         run: |
#           kubectl create namespace webgoat || true
#           kubectl create namespace monitoring || true
#           kubectl apply -f kubernetes/prometheus/
#           kubectl apply -f kubernetes/grafana/
#           kubectl apply -f kubernetes/deployment.yaml