# name: "Deploy WebGoat"

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'

#     - name: Install Ansible
#       run: |
#         python -m pip install --upgrade pip
#         pip install ansible kubernetes

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v2

#     - name: Configure SSH
#       run: |
#         mkdir -p ~/.ssh
#         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#         chmod 600 ~/.ssh/id_rsa
#         ssh-keyscan -H 20.63.16.243 >> ~/.ssh/known_hosts

#     - name: Run Ansible Playbook
#       run: |
#         echo "[webgoat]" > inventory.ini
#         echo "20.63.16.243 ansible_user=azureuser" >> inventory.ini
#         ansible-playbook -i inventory.ini ansible/deploy.yml

#     - name: Copy kubeconfig from VM
#       run: |
#         ssh -i ~/.ssh/id_rsa azureuser@20.63.16.243 'kubectl config view --raw' > ~/.kube/config
#         chmod 600 ~/.kube/config

#     - name: Terraform Init and Apply
#       run: |
#         cd infrastructure
#         terraform init
#         terraform apply -auto-approve